/**
 * @module lock
 * Lock flow: validate no open annotations, set frames to locked, generate DESIGN-SPEC.md,
 * build the implementation prompt, and optionally spawn agentCommand.
 *
 * POST /api/lock handler is exported and mounted in api.js.
 */

import { writeFileSync, renameSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';

import { loadProject, saveProject, loadAnnotations } from './board.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Atomic write of a text file (write to .tmp then rename).
 * @param {string} filePath
 * @param {string} text
 */
function atomicWriteText(filePath, text) {
  const tmp = filePath + '.tmp';
  writeFileSync(tmp, text, 'utf8');
  renameSync(tmp, filePath);
}

/**
 * Try to read pikaso.config.json from the board root's parent workspace.
 * @param {string} root  Board root (e.g. /workspace/.pikaso)
 * @returns {{ agentCommand?: string | null } | null}
 */
function readConfig(root) {
  // Config may live inside the board root, in the workspace root (parent of
  // .pikaso/), or in the parent's integrations/ directory.
  const candidates = [
    join(root, 'pikaso.config.json'),
    join(root, '..', 'integrations', 'pikaso.config.json'),
    join(root, '..', 'pikaso.config.json'),
  ];
  for (const p of candidates) {
    if (existsSync(p)) {
      try { return JSON.parse(readFileSync(p, 'utf8')); } catch { /* ignore */ }
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// DESIGN-SPEC.md generator
// ---------------------------------------------------------------------------

/**
 * Extract CSS custom property declarations from a frame's mockup to form its
 * token contract (the vocabulary an implementer must reuse).
 * @param {string} mockupPath
 * @returns {string[]} Lines like `--accent: #ff5a36;`
 */
function extractTokens(mockupPath) {
  try {
    const css = readFileSync(mockupPath, 'utf8');
    const out = [];
    for (const m of css.matchAll(/--[a-zA-Z][\w-]*\s*:\s*[^;{}]+;/g)) {
      const line = m[0].replace(/\s+/g, ' ').trim();
      if (!out.includes(line)) out.push(line);
      if (out.length >= 24) break;
    }
    return out;
  } catch {
    return [];
  }
}

/**
 * Build the markdown content for DESIGN-SPEC.md.
 * @param {import('./board.js').Project} project
 * @param {Array<{ frame: import('./board.js').Frame, annotations: import('./board.js').Annotation[] }>} frameData
 * @param {string} root  Board root directory (to locate each frame's mockup).
 * @returns {string}
 */
function buildDesignSpec(project, frameData, root) {
  const lines = [
    `# DESIGN-SPEC — ${project.name}`,
    '',
    `> Generated by Pikaso on ${new Date().toISOString()}`,
    `> ${frameData.length} frame${frameData.length !== 1 ? 's' : ''} locked for implementation.`,
    '',
    '---',
    '',
  ];

  for (const { frame, annotations } of frameData) {
    const resolved = annotations.filter(a => a.status === 'resolved');
    const open     = annotations.filter(a => a.status === 'open');

    lines.push(`## Frame: ${frame.name}`);
    lines.push('');
    lines.push(`- **Status:** locked`);
    lines.push(`- **Purpose:** ${frame.purpose ?? '—'}`);
    lines.push(`- **Viewport:** ${frame.w} × ${frame.h}px`);
    lines.push(`- **Position on board:** x=${frame.x}, y=${frame.y}`);
    lines.push('');

    // Token contract — CSS custom properties declared in the approved mockup
    const tokens = extractTokens(join(root, 'frames', frame.name, 'mockup.html'));
    lines.push('### Token contract');
    lines.push('');
    if (tokens.length > 0) {
      lines.push('```css');
      for (const t of tokens) lines.push(t);
      lines.push('```');
    } else {
      lines.push("_No CSS custom properties declared — match the mockup's literal values._");
    }
    lines.push('');

    // Final state
    lines.push('### Final state');
    lines.push('');
    lines.push(`- **Authoritative mockup:** \`frames/${frame.name}/mockup.html\` (self-contained)`);
    lines.push(`- **Locked at:** ${new Date().toISOString()}`);
    lines.push(`- **Annotations at lock time:** ${resolved.length} resolved, ${open.length} open`);
    lines.push('');

    if (resolved.length > 0) {
      lines.push(`### Resolved annotations (${resolved.length})`);
      lines.push('');
      for (const ann of resolved) {
        lines.push(`#### ${ann.id.slice(0, 8)} — resolved`);
        lines.push('');
        lines.push(`- **Selector:** \`${ann.type === 'freehand' ? '(freehand drawing)' : ann.selector}\``);
        lines.push(`- **Comment:** ${ann.text}`);
        lines.push(`- **Created:** ${ann.createdAt}`);
        lines.push(`- **Resolved:** ${ann.resolvedAt ?? 'unknown'}`);
        lines.push('');
      }
    }

    if (open.length > 0) {
      lines.push(`### ⚠ Open annotations (${open.length}) — unresolved at lock time`);
      lines.push('');
      for (const ann of open) {
        lines.push(`#### ${ann.id.slice(0, 8)} — open`);
        lines.push('');
        lines.push(`- **Selector:** \`${ann.type === 'freehand' ? '(freehand drawing)' : ann.selector}\``);
        lines.push(`- **Comment:** ${ann.text}`);
        lines.push(`- **Created:** ${ann.createdAt}`);
        lines.push('');
      }
    }

    if (resolved.length === 0 && open.length === 0) {
      lines.push('_No annotations for this frame._');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Implementation prompt builder
// ---------------------------------------------------------------------------

/**
 * Build the implementation prompt string.
 * @param {import('./board.js').Project} project
 * @param {Array<{ frame: import('./board.js').Frame, annotations: import('./board.js').Annotation[] }>} frameData
 * @param {string} specPath  Path to the DESIGN-SPEC.md that was written.
 * @returns {string}
 */
function buildPrompt(project, frameData, specPath) {
  const frameNames = frameData.map(d => `\`${d.frame.name}\``).join(', ');
  const totalResolved = frameData.reduce((n, d) => n + d.annotations.filter(a => a.status === 'resolved').length, 0);

  return `\
Implement the Pikaso design spec for "${project.name}".

The design has been locked after ${totalResolved} resolved annotation${totalResolved !== 1 ? 's' : ''} across ${frameData.length} frame${frameData.length !== 1 ? 's' : ''}: ${frameNames}.

Read the full specification at: ${specPath}

For each frame:
1. Read \`mockup.html\` to understand the final approved design.
2. Implement it in the actual product codebase, matching the HTML structure, colours, typography, and layout exactly.
3. Preserve resolved annotation decisions — those design choices are locked.

Do not alter the mockup files. Reference them; implement from them.
`;
}

// ---------------------------------------------------------------------------
// agentCommand adapter
// ---------------------------------------------------------------------------

/**
 * Attempt to send the prompt via agentCommand (bob --non-interactive, etc.).
 * Falls back to stdout if no command configured or if the spawn fails.
 * Also tries clipboard (clip / pbcopy / xclip) as secondary fallback.
 *
 * @param {string | null | undefined} agentCommand
 * @param {string} prompt
 * @returns {{ method: 'agent' | 'clipboard' | 'stdout' }}
 */
function dispatchPrompt(agentCommand, prompt) {
  // Primary: agentCommand — run as a shell command line so quoted arguments
  // (e.g. node -e "script with spaces") survive intact.
  if (agentCommand) {
    const result = spawnSync(agentCommand, {
      input: prompt,
      encoding: 'utf8',
      timeout: 30_000,
      shell: true,
    });
    if (result.status === 0) {
      return { method: 'agent' };
    }
    // Fall through on non-zero exit
  }

  // Secondary: clipboard
  const clipCmds = ['clip', 'pbcopy', 'xclip'];
  for (const clipCmd of clipCmds) {
    const r = spawnSync(clipCmd, [], { input: prompt, encoding: 'utf8', timeout: 5_000 });
    if (r.status === 0) return { method: 'clipboard' };
  }

  // Fallback: stdout
  process.stdout.write('\n[pikaso] Implementation prompt:\n\n');
  process.stdout.write(prompt);
  process.stdout.write('\n');
  return { method: 'stdout' };
}

// ---------------------------------------------------------------------------
// Lock handler
// ---------------------------------------------------------------------------

/**
 * Execute the lock flow.
 *
 * @param {string} root  Board root directory.
 * @param {{ run?: boolean }} [opts]
 *   - `run`: if true, attempt agentCommand dispatch (used by "Run with Bob Shell" button).
 * @returns {{
 *   specPath: string,
 *   prompt: string,
 *   framesLocked: number,
 *   dispatch?: { method: string }
 * }}
 * @throws {{ status: 409, openCount: number }} If open annotations exist.
 */
export async function lockBoard(root, opts = {}) {
  const project = loadProject(root);

  // Collect frame data
  const frameData = [];
  let totalOpen = 0;

  for (const frame of project.frames) {
    let annotations = [];
    try {
      annotations = loadAnnotations(root, frame.name);
    } catch {
      // Frame may have no annotations.json yet
    }
    const openCount = annotations.filter(a => a.status === 'open').length;
    totalOpen += openCount;
    frameData.push({ frame, annotations });
  }

  // Block if open annotations exist
  if (totalOpen > 0) {
    const err = Object.assign(
      new Error(`Cannot lock: ${totalOpen} open annotation${totalOpen !== 1 ? 's' : ''} remain`),
      { status: 409, openCount: totalOpen }
    );
    throw err;
  }

  // Set all frames to locked
  for (const frame of project.frames) {
    frame.status = 'locked';
  }
  saveProject(root, project);

  // Write DESIGN-SPEC.md atomically
  const specPath = join(root, 'DESIGN-SPEC.md');
  const specContent = buildDesignSpec(project, frameData, root);
  mkdirSync(root, { recursive: true });
  atomicWriteText(specPath, specContent);

  // Build implementation prompt
  const prompt = buildPrompt(project, frameData, specPath);

  // Dispatch
  let dispatch;
  if (opts.run !== false) {
    const config = readConfig(root);
    dispatch = dispatchPrompt(config?.agentCommand, prompt);
  }

  return {
    specPath,
    prompt,
    framesLocked: project.frames.length,
    dispatch,
  };
}
